framework:
  - terraform

severity-threshold: HIGH

skip-check:
  - CKV_AWS_144   # Cross-region replication (not required for demo)
  - CKV2_AWS_61   # S3 lifecycle (intentional gap for showcase)

output:
  - cli
