framework: terraform

# Only run a small, safe subset
check:
  - CKV_AWS_20    # S3 public read
  - CKV_AWS_130   # Subnets no public IP
  - CKV_AWS_145   # S3 KMS encryption
  - CKV_AWS_227   # KMS key enabled

soft_fail: true
